# apiVersion: v1
# kind: PersistentVolume
# metadata:
#  name: mysql-pv-volume
#  labels:
#    type: local
# spec:
#  storageClassName: manual
#  capacity:
#    storage: 1Gi
#  accessModes:
#  - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#  name: mysql-pv-claim
#  labels:
#    app: wordpress
# spec:
#  storageClassName: manual
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi

#---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: 
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: 
        app: mysql
    spec:
      containers:
      - name: database
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password 
#         valueFrom:
#           secretKeyRef:
#             name: mysql-pass
#             key: password
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD 
          value: password         
        - name: MYSQL_DATABASE
          value: wpdb
        ports:
        - containerPort: 3306
          name: mysql
#        volumeMounts:
#        - name: mysql-persistent-storage
#          mountPath: /var/lib/mysql
#      volumes:
#      - name: mysql-persistent-storage
#        persistentVolumeClaim:
#          claimName: mysql-pv-claim
