# apiVersion: v1
#  kind: PersistentVolumeClaim
#  metadata:
#  name: wp-pv-claim
#  labels:
#    app: wordpress
#  spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi

# ---
apiVersion: v1 
kind: Service 
metadata: 
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:php7.4-apache
        ports: 
        - containerPort: 80
          name: wordpress
        env: 
        - name: WORDPRESS_DB_HOST # host db
          value: mysql-service.default.svc.cluster.local
        - name: WORDPRESS_DB_USER
          value: wpuser 
        - name: WORDPRESS_DB_PASSWORD
          value: password 
        - name: WORDPRESS_DB_NAME
          value: wpdb 
        - name: WORDPRESS_DEBUG
          value: "1"
#        volumeMounts:
#        - name: wordpress-persistent-storage
#          mountPath: /var/www/html
#      volumes:
#      - name: wordpress-persistent-storage
#        persistentVolumeClaim:
#          claimName: wp-pv-claim
